# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "文章"
  pre="pencil"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  pre="bars"
  weight = 20

[[main]]
  name = "技术"
  pre="lightbulb"
  parent = "分类"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "音乐"
  pre="music"
  parent = "分类"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "生活"
  pre="mug-hot"
  parent = "分类"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "杂谈"
  pre="heart"
  parent = "分类"
  pageRef = "posts"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/b1narypoet"
  weight = 30

[[main]]
  identifier = "telegram"
  pre = "telegram"
  url = "https://t.me/LoopQuark"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
